use [SWEET FACTORY]
CREATE TABLE PROVIDER
(
	PROVIDER_ID integer  NOT NULL ,
	NAME varchar(20)  NOT NULL ,
	ADRESS varchar(20)  NOT NULL ,
	PHONE_NUMBER varchar(13)  NOT NULL
	CONSTRAINT XPKPROVIDER PRIMARY KEY  CLUSTERED (PROVIDER_ID ASC) 
)
go

CREATE TABLE RAWSTUFF_CATEGORY
(
	RAWSTUFF_CATEGORY_ID integer  NOT NULL ,
	NAME varchar(20)  NOT NULL 
	CONSTRAINT XPKRAWSTUFF_CATEGORY PRIMARY KEY  CLUSTERED (RAWSTUFF_CATEGORY_ID ASC)
)
go

CREATE TABLE RAWSTUFF_INFO
(
	RAWSTUFF_INFO_ID integer  NOT NULL ,
	NAME varchar(20)  NOT NULL ,
	INGREDIENTS varchar(50)  NOT NULL ,
	EXPIRE_DAYS integer  NOT NULL ,
	RAWSTUFF_ORDER_ID integer  NOT NULL ,
	RAWSTUFF_CATEGORY_ID integer  NOT NULL
	CONSTRAINT XPKRAWSTUFF_INFO PRIMARY KEY  CLUSTERED (RAWSTUFF_INFO_ID ASC),
	CONSTRAINT  R_18 FOREIGN KEY (RAWSTUFF_CATEGORY_ID) REFERENCES RAWSTUFF_CATEGORY(RAWSTUFF_CATEGORY_ID) 
)
go

CREATE TABLE REQURIED_RAWSTUFF
(
	RAWSTUFF_INFO_ID integer  NULL ,
	REQUIRED_RAWSTUFF_ID integer  NOT NULL ,
	QUANTITY integer  NULL
	CONSTRAINT XPKREQURIED_RAWSTUFF PRIMARY KEY  CLUSTERED (REQUIRED_RAWSTUFF_ID ASC),
	CONSTRAINT  R_19 FOREIGN KEY (RAWSTUFF_INFO_ID) REFERENCES RAWSTUFF_INFO(RAWSTUFF_INFO_ID)	
)
go

CREATE TABLE RAWSTUFF_STATE
(
	RAWSTUFF_STATE_ID integer  NOT NULL ,
	NAME varchar(20)  NOT NULL ,
	DESCRIPTION varchar(20)  NOT NULL
	CONSTRAINT XPKRAWSTUFF_STATE PRIMARY KEY  CLUSTERED (RAWSTUFF_STATE_ID ASC) 
)
go


CREATE TABLE ADDRESS
( 
	ADDRESS_ID           INTEGER  NOT NULL ,
	CITY                 VARCHAR(50)  NULL ,
	STREET               VARCHAR(50)  NOT NULL ,
	COUNTRY              VARCHAR(50)  NOT NULL ,
	REGION               VARCHAR(50)  NOT NULL ,
	BUILDING_NUMBER      INTEGER  NOT NULL ,
	CONSTRAINT XPKADDRESS PRIMARY KEY  CLUSTERED (ADDRESS_ID ASC)
)
GO



CREATE TABLE CLIENT
( 
	CLIENT_ID            INTEGER  NOT NULL ,
	CLIENT_NAME          VARCHAR(30)  NOT NULL ,
	CLIENT_SURNAME       VARCHAR(30)  NOT NULL ,
	CLIENT_MIDDLE_NAME   VARCHAR(30)  NULL ,
	COMPANY_TITLE        VARCHAR(MAX)  NULL ,
	MOBILE_PHONE         VARCHAR(20)   NULL ,
	COMPANY_PHONE        VARCHAR(20)   NULL ,
	EMAIL                VARCHAR(MAX)  NULL ,
	ADDRESS              INTEGER  NULL ,
	CONSTRAINT XPKCLIENT PRIMARY KEY  CLUSTERED (CLIENT_ID ASC),
	CONSTRAINT R_102 FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ADDRESS_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1CLIENT ON CLIENT
( 
	ADDRESS               ASC
)
GO



CREATE TABLE DEPARTMENT
( 
	DEPARTMENT_ID        INTEGER  NOT NULL ,
	DEPARTMENT_TITLE     VARCHAR(20)  NOT NULL ,
	CONSTRAINT XPKDEPARTMENT PRIMARY KEY  CLUSTERED (DEPARTMENT_ID ASC)
)
GO



CREATE TABLE POST
( 
	POST_ID              INTEGER  NOT NULL ,
	POST_NAME            VARCHAR(50)  NOT NULL ,
	DEPARTMENT_ID        INTEGER  NOT NULL ,
	CONSTRAINT XPKPOSITION PRIMARY KEY  CLUSTERED (POST_ID ASC),
	CONSTRAINT R_79 FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1POSITION ON POST
( 
	DEPARTMENT_ID         ASC
)
GO



CREATE TABLE STAFF
( 
	STAFF_NAME           VARCHAR(30)  NOT NULL ,
	STAFF_ID             INTEGER  NOT NULL ,
	BIRTH_DATE           DATE   NULL ,
	POST_ID              INTEGER  NOT NULL ,
	STAFF_SURNAME        VARCHAR(30)   NULL ,
	MOBILE_PHONE         VARCHAR(20)  NULL ,
	EMAIL                VARCHAR(MAX)  NULL ,
	ADDRESS              INTEGER   NULL ,
	LOGIN				 VARCHAR(20) NOT NULL ,
	PASSWORD             VARCHAR(20) NOT NULL ,
	FULL_SALARY          NUMERIC(10,4) NOT NULL DEFAULT 100 ,
	CONSTRAINT XPKSTAFF PRIMARY KEY  CLUSTERED (STAFF_ID ASC),
	CONSTRAINT R_83 FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
	,CONSTRAINT R_101 FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ADDRESS_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1STAFF ON STAFF
( 
	POST_ID               ASC
)
GO



CREATE NONCLUSTERED INDEX XIF2STAFF ON STAFF
( 
	ADDRESS               ASC
)
GO


CREATE TABLE SALE_ORDER
( 
	SALE_ORDER_ID        INTEGER  NOT NULL ,
	CLIENT_ID            INTEGER  NOT NULL ,
	ORDER_DATE           DATE  NOT NULL ,
	REQUIRED_DATE        DATE  NOT NULL ,
	ORDER_STATUS         VARCHAR(20) NOT NULL ,
	DELIVERY_STATUS      VARCHAR(20)  NOT NULL ,
	DISCOUNT             MONEY  NOT NULL ,
	TOTAL                MONEY  NOT NULL ,
	PAID                MONEY  NOT NULL ,
	STAFF_ID             INTEGER  NOT NULL ,
	CONSTRAINT XPKSALE_ORDER PRIMARY KEY  CLUSTERED (SALE_ORDER_ID ASC),
	CONSTRAINT R_41 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
	CONSTRAINT R_43 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1SALE_ORDER ON SALE_ORDER
( 
	CLIENT_ID             ASC
)
GO



CREATE NONCLUSTERED INDEX XIF2SALE_ORDER ON SALE_ORDER
( 
	STAFF_ID              ASC
)
GO



CREATE TABLE CATEGORY
( 
	CATEGORY_ID          INTEGER  NOT NULL ,
	CATEGORY_TITLE       NVARCHAR(MAX)  NOT NULL ,
	CONSTRAINT XPKCATEGORY PRIMARY KEY  CLUSTERED (CATEGORY_ID ASC)
)
GO



CREATE TABLE PACKAGE_DESCRIPTION
( 
	PACK_DESCR_ID        INTEGER  NOT NULL ,
	WIDTH                NUMERIC(18,2)  NOT NULL ,
	HEIGTH               NUMERIC(18,2)  NOT NULL ,
	LENGTH               NUMERIC(18,2)  NOT NULL ,
	CONSTRAINT XPKPACKAGE_DESCRIPTION PRIMARY KEY  CLUSTERED (PACK_DESCR_ID ASC)
)
GO



CREATE TABLE PRODUCT_INFO
( 
	CATEGORY_ID          INTEGER  NOT NULL ,
	PRODUCT_INFO_ID      INTEGER  NOT NULL ,
	PRODUCT_TITLE        VARCHAR(MAX) NOT  NULL ,
	PRODUCT_DESCRIPTION  TEXT  NULL ,
	QUANTITY_IN_PACKAGE  INTEGER  NOT NULL ,
	PACK_DESCR_ID        INTEGER  NOT NULL ,
	PRODUCTION_PRICE     MONEY  NOT NULL ,
	CONSTRAINT XPKPRODUCT PRIMARY KEY  CLUSTERED (PRODUCT_INFO_ID ASC),
	CONSTRAINT R_89 FOREIGN KEY (PACK_DESCR_ID) REFERENCES PACKAGE_DESCRIPTION(PACK_DESCR_ID),
	CONSTRAINT R_40 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF2PRODUCT ON PRODUCT_INFO
( 
	PACK_DESCR_ID         ASC
)
GO



CREATE NONCLUSTERED INDEX XIF1PRODUCT ON PRODUCT_INFO
( 
	CATEGORY_ID           ASC
)
GO



CREATE TABLE ORDER_PRODUCT
( 
	ORDER_PRODUCT_INFO_ID     INTEGER  NOT NULL ,
	SALE_ORDER_ID        INTEGER  NOT NULL ,
	PRODUCT_INFO_ID           INTEGER  NOT NULL ,
	QUANTITY_IN_ORDER    INTEGER  NOT NULL ,
	CONSTRAINT XPKORDER_PRODUCT PRIMARY KEY  CLUSTERED (ORDER_PRODUCT_INFO_ID ASC),
	CONSTRAINT R_105 FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO(PRODUCT_INFO_ID),
	CONSTRAINT R_103 FOREIGN KEY (SALE_ORDER_ID) REFERENCES SALE_ORDER(SALE_ORDER_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF2ORDER_PRODUCT ON ORDER_PRODUCT
( 
	PRODUCT_INFO_ID            ASC
)
GO



CREATE NONCLUSTERED INDEX XIF1ORDER_PRODUCT ON ORDER_PRODUCT
( 
	SALE_ORDER_ID         ASC
)
GO



CREATE TABLE WAREHOUSE
( 
	WAREHOUSE_ID         INTEGER  NOT NULL ,
	CAPACITY             MONEY  NOT NULL ,
	FREE_SPACE           NUMERIC(18,2)  NOT NULL ,
	PHONE_NUMBER         VARCHAR(20)  NULL ,
	ADDRESS              INTEGER  NULL ,
	FAX                  VARCHAR(20)  NULL ,
	STAFF_ID             INTEGER NOT NULL 
	CONSTRAINT XPKWAREHOUSE PRIMARY KEY  CLUSTERED (WAREHOUSE_ID ASC),
	CONSTRAINT R_98 FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT R_128 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
)
GO


CREATE NONCLUSTERED INDEX XIF1WAREHOUSE ON WAREHOUSE
( 
	ADDRESS               ASC
)
GO



CREATE TABLE RELEASED_PRODUCT
( 
	RELEASED_PRODUCT_INFO_ID  INTEGER  NOT NULL ,
	PRODUCTION_DATE      DATE  NOT NULL ,
	EXPIRED_DATE         DATE  NOT NULL ,
	PRODUCT_INFO_ID      INTEGER  NOT NULL ,
	WAREHOUSE_ID         INTEGER  NOT NULL ,
	QUANTITY             INTEGER  NOT NULL ,
	MANUFACTURER_ADDRESS INTEGER  NOT NULL ,
	
	CONSTRAINT XPKRELEASED_PRODUCT PRIMARY KEY  CLUSTERED (RELEASED_PRODUCT_INFO_ID ASC),
	CONSTRAINT R_95 FOREIGN KEY (MANUFACTURER_ADDRESS) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT R_87 FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID),
	CONSTRAINT R_120 FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO(PRODUCT_INFO_ID)
)
GO


CREATE NONCLUSTERED INDEX XIF1RELEASED_PRODUCT ON RELEASED_PRODUCT
( 
	PRODUCT_INFO_ID            ASC
)
GO



CREATE NONCLUSTERED INDEX XIF3RELEASED_PRODUCT ON RELEASED_PRODUCT
( 
	MANUFACTURER_ADDRESS  ASC
)
GO



CREATE NONCLUSTERED INDEX XIF2RELEASED_PRODUCT ON RELEASED_PRODUCT
( 
	WAREHOUSE_ID          ASC
)
GO



CREATE TABLE SALARY
( 
	SALARY_ID            INTEGER  NOT NULL ,
	SALARY_VALUE         MONEY  NOT NULL ,
	CHANGED_DATE         DATE  NOT NULL ,
	POST_ID              INTEGER  NOT NULL ,
	CONSTRAINT XPKSALARY PRIMARY KEY  CLUSTERED (SALARY_ID ASC),
	CONSTRAINT R_78 FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF2SALARY ON SALARY
( 
	POST_ID               ASC
)
GO



CREATE TABLE DELIVERY_ADDRESS
( 
	DEL_ADDRESS_ID       INTEGER  NOT NULL ,
	DELIVERY_ADDRESS_FROM INTEGER  NOT NULL ,
	DELIVERY_ADDRESS_TO  INTEGER  NOT NULL ,
	DISTANCE           NUMERIC(18,2)  NOT NULL ,
	CONSTRAINT XPKDELIVERY_ADDRESS PRIMARY KEY  CLUSTERED (DEL_ADDRESS_ID ASC),
	CONSTRAINT R_93 FOREIGN KEY (DELIVERY_ADDRESS_TO) REFERENCES ADDRESS(ADDRESS_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1DELIVERY_ADDRESS ON DELIVERY_ADDRESS
( 
	DELIVERY_ADDRESS_TO   ASC
)
GO



CREATE TABLE DELIVERY
( 
	SALE_ORDER_ID        INTEGER  NOT NULL ,
	DELIVERY_ID          INTEGER  NOT NULL ,
	DELIVERY_DATE        DATE  NOT NULL ,
	DELIVERY_TOTAL       MONEY  NULL ,
	DEL_ADDRESS_ID       INTEGER  NOT NULL ,
	COST_PER_KM			 MONEY  NOT NULL ,
	CONSTRAINT XPKDELIVERY PRIMARY KEY  CLUSTERED (DELIVERY_ID ASC),
	CONSTRAINT R_45 FOREIGN KEY (SALE_ORDER_ID) REFERENCES SALE_ORDER(SALE_ORDER_ID),
	CONSTRAINT R_92 FOREIGN KEY (DEL_ADDRESS_ID) REFERENCES DELIVERY_ADDRESS(DEL_ADDRESS_ID)
)
GO



CREATE NONCLUSTERED INDEX XIF1DELIVERY ON DELIVERY
( 
	SALE_ORDER_ID         ASC
)
GO



CREATE NONCLUSTERED INDEX XIF2DELIVERY ON DELIVERY
( 
	DEL_ADDRESS_ID        ASC
)
GO


CREATE TABLE PRODUCTION_SCHEDULE
( 
	SCHEDULE_ID          INTEGER  NOT NULL ,
	REQUIRED_DATE        DATE  NOT NULL ,
	STAFF_ID             INTEGER  NOT NULL ,
	CREATED_DATE         DATE  NOT NULL ,
	SCHEDULE_STATE       VARCHAR(20)  NOT NULL ,
	SCHEDULE_TOTAL       MONEY  NOT NULL ,
	WAREHOUSE_ID         INTEGER NOT NULL 
	CONSTRAINT XPKPRODUCTION_SCHEDULE PRIMARY KEY  CLUSTERED (SCHEDULE_ID ASC),
	CONSTRAINT R_47 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
	CONSTRAINT R_129 FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID)
)
GO


CREATE NONCLUSTERED INDEX XIF1PRODUCTION_SCHEDULE ON PRODUCTION_SCHEDULE
( 
	STAFF_ID              ASC
)
GO



CREATE TABLE RAWSTUFF
(
	WAREHOUSE_ID integer  NOT NULL ,
	RAWSTUFF_ID integer  NOT NULL ,
	AMOUNT integer  NOT NULL ,
	RAWSTUFF_INFO_ID integer  NOT NULL ,
	RAWSTUFF_STATE_ID integer  NOT NULL ,
	EXPIRE_DATE DATE  NOT NULL
	CONSTRAINT XPKRAWSTUFF PRIMARY KEY  CLUSTERED (RAWSTUFF_ID ASC),
	CONSTRAINT  R_2 FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID),
	CONSTRAINT  R_5 FOREIGN KEY (RAWSTUFF_INFO_ID) REFERENCES RAWSTUFF_INFO(RAWSTUFF_INFO_ID),
	CONSTRAINT  R_6 FOREIGN KEY (RAWSTUFF_STATE_ID) REFERENCES RAWSTUFF_STATE(RAWSTUFF_STATE_ID) 
)
go

CREATE TABLE INGREDIENTS
( 
	INGREDIENTS_ID        INTEGER  NOT NULL ,
    RAWSTUFF_ID            INTEGER  NOT NULL ,
	PRODUCT_INFO_ID            INTEGER  NOT NULL ,
	CONSTRAINT XPKINGREDIENTS_ID PRIMARY KEY  CLUSTERED (INGREDIENTS_ID ASC),
	CONSTRAINT R_90 FOREIGN KEY (RAWSTUFF_ID) REFERENCES RAWSTUFF(RAWSTUFF_ID),
	CONSTRAINT R_91 FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO(PRODUCT_INFO_ID)
)
GO

CREATE TABLE RAWSTUFF_DELIVERY
(
	RAWSTUFF_DELIVERY_ID integer  NOT NULL ,
	RAWSTUFF_ID integer  NOT NULL ,
	DELIVERY_DATE DATE  NOT NULL ,
	AMOUNT integer  NOT NULL ,
	PRICE money  NOT NULL	
	CONSTRAINT XPKRAWSTUFF_DELIVERY PRIMARY KEY  CLUSTERED (RAWSTUFF_DELIVERY_ID ASC)
	CONSTRAINT  R_15 FOREIGN KEY (RAWSTUFF_ID) REFERENCES RAWSTUFF(RAWSTUFF_ID) 
)
go


CREATE TABLE RAWSTUFF_ORDER
(
	RAWSTUFF_ORDER_ID integer  NOT NULL ,
	CREATED_DATE DATE  NOT NULL ,
	PROVIDER_ID integer  NOT NULL ,
	DELIVERY_ID integer  NOT NULL
	CONSTRAINT XPKORDER PRIMARY KEY  CLUSTERED (RAWSTUFF_ORDER_ID ASC) ,
	CONSTRAINT  R_7 FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(PROVIDER_ID),
	CONSTRAINT  R_13 FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY(DELIVERY_ID)
)

CREATE TABLE SCHEDULE_PRODUCT_INFO
( 
	SCHEDULE_PRODUCT_INFO_ID  INTEGER  NOT NULL ,
	SCHEDULE_ID			 INTEGER  NOT NULL ,
	PRODUCT_INFO_ID      INTEGER  NOT NULL ,
	QUANTITY_IN_SCHEDULE INTEGER  NOT NULL ,
	RELEASED_QUANTITY    INTEGER  NOT NULL ,
	CONSTRAINT XPKPSCHEDULE_PRODUCT_INFO PRIMARY KEY  CLUSTERED (SCHEDULE_PRODUCT_INFO_ID ASC),
	CONSTRAINT R_115 FOREIGN KEY (SCHEDULE_ID) REFERENCES PRODUCTION_SCHEDULE(SCHEDULE_ID),
    CONSTRAINT R_116 FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO(PRODUCT_INFO_ID)
)
GO


CREATE NONCLUSTERED INDEX XIF2SCHEDULE_PRODUCT_INFO ON SCHEDULE_PRODUCT_INFO
( 
	PRODUCT_INFO_ID            ASC
)
GO

CREATE NONCLUSTERED INDEX XIF1Schedule ON SCHEDULE_PRODUCT_INFO
( 
	SCHEDULE_ID	         ASC
)
go

CREATE TABLE PRODUCT_PRICE
( 
	PRICE_ID             INTEGER  NOT NULL IDENTITY(1,1),--AUTOINCREMENT--
	PERSENTAGE_VALUE     NUMERIC(10,5)  NOT NULL ,
	CHANGED_DATE         DATETIME NOT NULL ,
	PRODUCT_INFO_ID      INTEGER  NOT NULL ,
	STAFF_ID              INTEGER  NOT NULL ,
	PRICE_VALUE          MONEY  NOT NULL 
	CONSTRAINT XPKPRODUCT_PRICE PRIMARY KEY  CLUSTERED (PRICE_ID ASC),
	CONSTRAINT R_125 FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO(PRODUCT_INFO_ID),
	CONSTRAINT R_126 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
)
GO

CREATE TRIGGER InsertTrigger on PRODUCT_INFO
AFTER INSERT
AS
BEGIN
	INSERT INTO [dbo].[PRODUCT_PRICE]
           ([PERSENTAGE_VALUE]
           ,[CHANGED_DATE]
           ,[PRODUCT_INFO_ID]
           ,[STAFF_ID]
           ,[PRICE_VALUE])
		   --STAFF_ID = 1 - перші зміни ціни від імені директора
	  (
		   SELECT 120, GETDATE(), PRODUCT_INFO_ID, 1, PRODUCTION_PRICE*1.2
		   FROM inserted
	  )
END;
GO