//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS_VIEW
    {
        public string Імя { get; set; }
        public string Прізвище { get; set; }
        public string По_батькові { get; set; }
        public string Компанія { get; set; }
        public string Мобільний { get; set; }
        public string Телефон_компанії { get; set; }
        public string email { get; set; }
        public string Місто { get; set; }
        public string Вулиця { get; set; }
        public string Країна { get; set; }
        public string Регіон { get; set; }
        public int Номер_будинку { get; set; }
    }
}
