//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.SALE_ORDER = new HashSet<SALE_ORDER>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_SURNAME { get; set; }
        public string CLIENT_MIDDLE_NAME { get; set; }
        public string COMPANY_TITLE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ADDRESS { get; set; }
    
        public virtual ADDRESS ADDRESS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_ORDER> SALE_ORDER { get; set; }
    }
}
