//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY()
        {
            this.RAWSTUFF_ORDER = new HashSet<RAWSTUFF_ORDER>();
        }
    
        public int SALE_ORDER_ID { get; set; }
        public int DELIVERY_ID { get; set; }
        public System.DateTime DELIVERY_DATE { get; set; }
        public Nullable<decimal> DELIVERY_TOTAL { get; set; }
        public int DEL_ADDRESS_ID { get; set; }
        public decimal COST_PER_KM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAWSTUFF_ORDER> RAWSTUFF_ORDER { get; set; }
        public virtual SALE_ORDER SALE_ORDER { get; set; }
        public virtual DELIVERY_ADDRESS DELIVERY_ADDRESS { get; set; }
    }
}
