//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTS
    {
        public int INGREDIENTS_ID { get; set; }
        public int RAWSTUFF_ID { get; set; }
        public int PRODUCT_INFO_ID { get; set; }
    
        public virtual RAWSTUFF RAWSTUFF { get; set; }
        public virtual PRODUCT_INFO PRODUCT_INFO { get; set; }
    }
}
