//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_PRODUCT
    {
        public int ORDER_PRODUCT_INFO_ID { get; set; }
        public int SALE_ORDER_ID { get; set; }
        public int PRODUCT_INFO_ID { get; set; }
        public int QUANTITY_IN_ORDER { get; set; }
        public Nullable<int> WAREHOUSE_ID { get; set; }
    
        public virtual SALE_ORDER SALE_ORDER { get; set; }
        public virtual PRODUCT_INFO PRODUCT_INFO { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
