//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_PRICE
    {
        public int PRICE_ID { get; set; }
        public decimal PERSENTAGE_VALUE { get; set; }
        public System.DateTime CHANGED_DATE { get; set; }
        public int PRODUCT_INFO_ID { get; set; }
        public int STAFF_ID { get; set; }
        public decimal PRICE_VALUE { get; set; }
    
        public virtual PRODUCT_INFO PRODUCT_INFO { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
