//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWSTUFF_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAWSTUFF_INFO()
        {
            this.RAWSTUFF = new HashSet<RAWSTUFF>();
            this.REQURIED_RAWSTUFF = new HashSet<REQURIED_RAWSTUFF>();
        }
    
        public int RAWSTUFF_INFO_ID { get; set; }
        public string NAME { get; set; }
        public string INGREDIENTS { get; set; }
        public int EXPIRE_DAYS { get; set; }
        public int RAWSTUFF_ORDER_ID { get; set; }
        public int RAWSTUFF_CATEGORY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAWSTUFF> RAWSTUFF { get; set; }
        public virtual RAWSTUFF_CATEGORY RAWSTUFF_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQURIED_RAWSTUFF> REQURIED_RAWSTUFF { get; set; }
    }
}
