//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWSTUFF_ORDER
    {
        public int RAWSTUFF_ORDER_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int PROVIDER_ID { get; set; }
        public int DELIVERY_ID { get; set; }
    
        public virtual DELIVERY DELIVERY { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
