//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWSTUFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAWSTUFF()
        {
            this.INGREDIENTS = new HashSet<INGREDIENTS>();
            this.RAWSTUFF_DELIVERY = new HashSet<RAWSTUFF_DELIVERY>();
        }
    
        public int WAREHOUSE_ID { get; set; }
        public int RAWSTUFF_ID { get; set; }
        public int AMOUNT { get; set; }
        public int RAWSTUFF_INFO_ID { get; set; }
        public int RAWSTUFF_STATE_ID { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGREDIENTS> INGREDIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAWSTUFF_DELIVERY> RAWSTUFF_DELIVERY { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual RAWSTUFF_INFO RAWSTUFF_INFO { get; set; }
        public virtual RAWSTUFF_STATE RAWSTUFF_STATE { get; set; }
    }
}
