//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWSTUFF_DELIVERY
    {
        public int RAWSTUFF_DELIVERY_ID { get; set; }
        public int RAWSTUFF_ID { get; set; }
        public System.DateTime DELIVERY_DATE { get; set; }
        public int AMOUNT { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual RAWSTUFF RAWSTUFF { get; set; }
    }
}
