//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELEASED_PRODUCT
    {
        public int RELEASED_PRODUCT_INFO_ID { get; set; }
        public System.DateTime PRODUCTION_DATE { get; set; }
        public System.DateTime EXPIRED_DATE { get; set; }
        public int PRODUCT_INFO_ID { get; set; }
        public int WAREHOUSE_ID { get; set; }
        public int QUANTITY { get; set; }
        public int MANUFACTURER_ADDRESS { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual PRODUCT_INFO PRODUCT_INFO { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
