//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQURIED_RAWSTUFF
    {
        public Nullable<int> RAWSTUFF_INFO_ID { get; set; }
        public int REQUIRED_RAWSTUFF_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual RAWSTUFF_INFO RAWSTUFF_INFO { get; set; }
    }
}
