//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_ORDER()
        {
            this.DELIVERY = new HashSet<DELIVERY>();
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
        }
    
        public int SALE_ORDER_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public System.DateTime REQUIRED_DATE { get; set; }
        public string ORDER_STATUS { get; set; }
        public string DELIVERY_STATUS { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal TOTAL { get; set; }
        public decimal PAID { get; set; }
        public int STAFF_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY> DELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
