//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.PRODUCT_PRICE = new HashSet<PRODUCT_PRICE>();
            this.PRODUCTION_SCHEDULE = new HashSet<PRODUCTION_SCHEDULE>();
            this.SALE_ORDER = new HashSet<SALE_ORDER>();
            this.WAREHOUSE = new HashSet<WAREHOUSE>();
        }
    
        public string STAFF_NAME { get; set; }
        public int STAFF_ID { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public int POST_ID { get; set; }
        public string STAFF_SURNAME { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ADDRESS { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public decimal FULL_SALARY { get; set; }
        public int THEME { get; set; }
    
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual POST POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_PRICE> PRODUCT_PRICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_SCHEDULE> PRODUCTION_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_ORDER> SALE_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE> WAREHOUSE { get; set; }
    }
}
