//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUFF_VIEW
    {
        public string Імя { get; set; }
        public string Прізвище { get; set; }
        public string Мобільний { get; set; }
        public string Посада { get; set; }
        public decimal Заробітна_плата { get; set; }
        public string Відділ { get; set; }
    }
}
