//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkDB_DudasVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE()
        {
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
            this.PRODUCTION_SCHEDULE = new HashSet<PRODUCTION_SCHEDULE>();
            this.RAWSTUFF = new HashSet<RAWSTUFF>();
            this.RELEASED_PRODUCT = new HashSet<RELEASED_PRODUCT>();
        }
    
        public int WAREHOUSE_ID { get; set; }
        public decimal CAPACITY { get; set; }
        public decimal ENGAGED_SPACE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<int> ADDRESS { get; set; }
        public string FAX { get; set; }
        public int STAFF_ID { get; set; }
    
        public virtual ADDRESS ADDRESS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_SCHEDULE> PRODUCTION_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAWSTUFF> RAWSTUFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASED_PRODUCT> RELEASED_PRODUCT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
